NetworkMVC/Controllers/LogInLogOutController.cs
using Entities;
using INetwork.BLL;
using NetworkBLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NetworkMVC.Controllers
{
    public class LogInLogOutController : Controller
    {
    
        private readonly INetworkLogic networkLogic;

        public LogInLogOutController()
        {
            this.networkLogic = new NetworkLogic();
        }

        // GET: Login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login([Bind(Include = "Login, Password")] User user)
        {
            bool exist = networkLogic.LogIn(user.Login, user.Password) != null ? true : false;
            ViewBag.LogIn = exist;
            return View();
        }


        [Authorize]
        public ActionResult Logout()
        {
            return View();
        }
    }
}

NetworkMVC/Controllers/MainPageController.cs
using Entities;
using INetwork.BLL;
using NetworkBLL;
using NetworkDLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NetworkMVC.Controllers
{
    public class MainPageController : Controller
    {

        private readonly INetworkLogic networkLogic;

        public MainPageController()
        {
            this.networkLogic = new NetworkLogic();
        }

        // GET: MainPage
        
        [HttpGet]
        public ActionResult SingUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SingUp(User user)
        {
            if (ModelState.IsValid)
            {
                networkLogic.SingUp(user);
                return Redirect($"~/LogInLogOut/Login");
            }
            else
            {
                LoggerUtil.getLog("Logger").Info("New user wasnt added cause bad model!");
                return View();
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            return View(networkLogic.GetByLogin(User.Identity.Name));
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditPersonInfo()
        {
            return View(networkLogic.GetByLogin(User.Identity.Name));
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditPersonInfo(User u)
        {
            if (ModelState.IsValid)
            {
                networkLogic.Edit(u);
                return Redirect("Index");
            }
            else
            {
                LoggerUtil.getLog("Logger").Info("Editing was refused cause bad model!");
                return View();
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Friends()
        {
            return View(networkLogic.GetAllFriends(User.Identity.Name));
        }

        [Authorize(Roles ="admin")]
        [HttpGet]
        public ActionResult GetAllUsers()
        {
            return View(networkLogic.GetAllUsers());
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult DeleteUsers()
        {
            if (Request["Delete"] != null)
            {
                networkLogic.DeleteUsers();
            }

            return Redirect("GetAllUsers");
        }
    }
}

NetworkMVC/Controllers/MessageController.cs
using Entities;
using INetwork.BLL;
using NetworkBLL;
using NetworkMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NetworkMVC.Views
{
    public class MessageController : Controller
    {

        private readonly INetworkLogic networkLogic;

        public MessageController()
        {
            this.networkLogic = new NetworkLogic();
        }

        // GET: Message
        [Authorize]
        [HttpGet]
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(GetMs(networkLogic.GetByLogin(User.Identity.Name).IDUser, id));
        }

        [Authorize]
        [HttpPost]
        public ActionResult Index([Bind(Include = "idFriend, message")] int? idFriend, string message)
        {
            if (idFriend == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int? id = networkLogic.GetByLogin(User.Identity.Name).IDUser;
            networkLogic.SendMessage(id, idFriend, message);
           
            return View(GetMs(id, idFriend));
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult GetAllMessages()
        {
            return View(networkLogic.GetAllMessages());
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult DeleteMessages()
        {
            if (Request["Delete"] != null)
            {
                networkLogic.DeleteMessages();
            }

            return Redirect("GetAllMessages");
        }

        private IEnumerable<MessageWithNames> GetMs(int? id, int? idFriend)
        {
            var ms = new List<MessageWithNames>();
            foreach (Message m in networkLogic.GetMessagesByFriend(id, idFriend))
            {
                if (m.IDUser == id)
                {
                    ms.Add(new MessageWithNames(m, networkLogic.GetById(idFriend).Name, networkLogic.GetById(id).Name));
                }
                else
                {
                    ms.Add(new MessageWithNames(m, networkLogic.GetById(id).Name, networkLogic.GetById(idFriend).Name));
                }
            }
            return ms.AsEnumerable();
        }

    }
}

NetworkMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Social network</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Log in", "Login", "LogInLogOut", new { area = "" }, new { @class = "navbar-brand"})|
                @Html.ActionLink("Sing up", "SingUp", "MainPage", new { area = "" }, new { @class = "navbar-brand" })

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Social network</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NetworkMVC/Views/Shared/_LayoutLogged.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Social network</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Social network", "Index", "MainPage", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Log out", "Logout", "LogInLogOut", new { area = "" }, new { @class = "navbar-brand" })
                @{
                    if (User.IsInRole("admin"))
                    {
                        @Html.ActionLink("Get all messages", "GetAllMessages", "Message", new { area = "" }, new { @class = "navbar-brand" });
                        @Html.ActionLink("Get all users", "GetAllUsers", "MainPage", new { area = "" }, new { @class = "navbar-brand" });
                    }
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Friends", "Friends", "MainPage")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Social network</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NetworkMVC/Views/Shared/_PartialSearch.cshtml
@model IEnumerable<Entities.UserSearch>

@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.IDUser })
                </td>
            </tr>
        }
    </table>
}
<div>
    @Html.ActionLink("Back to Profile", "Index", "MainPage") /
    @Html.ActionLink("Another search", "Friends", "MainPage")
</div>