NetworkMVC/Controllers/MainPageController.cs
using Entities;
using INetwork.BLL;
using NetworkBLL;
using NetworkDLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NetworkMVC.Controllers
{
    public class MainPageController : Controller
    {

        private readonly INetworkLogic networkLogic;

        public MainPageController()
        {
            this.networkLogic = new NetworkLogic();
        }

        // GET: MainPage
        
        [HttpGet]
        public ActionResult SingUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SingUp(User user)
        {
            if (ModelState.IsValid)
            {
                networkLogic.SingUp(user);
                return Redirect($"~/LogInLogOut/Login");
            }
            else
            {
                LoggerUtil.getLog("Logger").Info("New user wasnt added cause bad model!");
                return View();
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            return View(networkLogic.GetByLogin(User.Identity.Name));
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditPersonInfo()
        {
            return View(networkLogic.GetByLogin(User.Identity.Name));
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditPersonInfo(User u)
        {
            if (ModelState.IsValid)
            {
                networkLogic.Edit(u);
                return Redirect("Index");
            }
            else
            {
                LoggerUtil.getLog("Logger").Info("Editing was refused cause bad model!");
                return View();
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Friends()
        {
            return View(networkLogic.GetAllFriends(User.Identity.Name));
        }

        [Authorize(Roles ="admin")]
        [HttpGet]
        public ActionResult GetAllUsers()
        {
            return View(networkLogic.GetAllUsers());
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult DeleteUsers()
        {
            if (Request["Delete"] != null)
            {
                networkLogic.DeleteUsers();
            }

            return Redirect("GetAllUsers");
        }
    }
}

NetworkMVC/Controllers/MessageController.cs
using Entities;
using INetwork.BLL;
using NetworkBLL;
using NetworkMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NetworkMVC.Views
{
    public class MessageController : Controller
    {

        private readonly INetworkLogic networkLogic;

        public MessageController()
        {
            this.networkLogic = new NetworkLogic();
        }

        // GET: Message
        [Authorize]
        [HttpGet]
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(GetMs(networkLogic.GetByLogin(User.Identity.Name).IDUser, id));
        }

        [Authorize]
        [HttpPost]
        public ActionResult Index([Bind(Include = "idFriend, message")] int? idFriend, string message)
        {
            if (idFriend == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int? id = networkLogic.GetByLogin(User.Identity.Name).IDUser;
            networkLogic.SendMessage(id, idFriend, message);
           
            return View(GetMs(id, idFriend));
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult GetAllMessages()
        {
            return View(networkLogic.GetAllMessages());
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult DeleteMessages()
        {
            if (Request["Delete"] != null)
            {
                networkLogic.DeleteMessages();
            }

            return Redirect("GetAllMessages");
        }

        private IEnumerable<MessageWithNames> GetMs(int? id, int? idFriend)
        {
            var ms = new List<MessageWithNames>();
            foreach (Message m in networkLogic.GetMessagesByFriend(id, idFriend))
            {
                if (m.IDUser == id)
                {
                    ms.Add(new MessageWithNames(m, networkLogic.GetById(idFriend).Name, networkLogic.GetById(id).Name));
                }
                else
                {
                    ms.Add(new MessageWithNames(m, networkLogic.GetById(id).Name, networkLogic.GetById(idFriend).Name));
                }
            }
            return ms.AsEnumerable();
        }

    }
}

NetworkMVC/Controllers/SearchController.cs
using Entities;
using INetwork.BLL;
using NetworkBLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NetworkMVC.Controllers
{
    public class SearchController : Controller
    {

        private readonly INetworkLogic networkLogic;

        public SearchController()
        {
            this.networkLogic = new NetworkLogic();
        }


        [HttpGet]
        [Authorize]
        public ActionResult SearchByName()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult SearchByName(string Name)
        {
            if (ModelState.IsValid)
            {
                var tmp = networkLogic.SearchByName(Name);
                return View(tmp);
            }

            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult SearchByPhone()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult SearchByPhone(string Phone)
        {
            if (ModelState.IsValid)
            {
                var tmp = networkLogic.SearchByPhone(Phone);
                return View(tmp);
            }

            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult SearchBySurname()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult SearchBySurname(string Surname)
        {
            if (ModelState.IsValid)
            {
                var tmp = networkLogic.SearchBySurname(Surname);
                return View(tmp);
            }

            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult SearchByTown()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult SearchByTown(string Town)
        {
            if (ModelState.IsValid)
            {
                var tmp = networkLogic.SearchByTown(Town);
                return View(tmp);
            }

            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.isFriend = networkLogic.GetAllFriends(User.Identity.Name).FirstOrDefault(x => x.IDUser == id) == null ? false : true;
            ViewBag.isUserHimself = networkLogic.GetById(id).Login.Equals(networkLogic.GetByLogin(User.Identity.Name).Login);
            return View(networkLogic.GetById(id));
        }

        [ActionName("Details")]
        [HttpPost]
        [Authorize]
        public ActionResult Details_Post([Bind(Include = "idUser")] int? idUser)
        {
            if (Request["Add"] != null)
            {
                networkLogic.AddFriend(networkLogic.GetByLogin(User.Identity.Name).IDUser, idUser);
            }
            else if (Request["Remove"] != null)
            {
                networkLogic.DeleteFriend(networkLogic.GetByLogin(User.Identity.Name).IDUser, idUser);
            }
            return Redirect("~/MainPage/Friends");
        }
    }
}

NetworkMVC/Views/MainPage/EditPersonInfo.cshtml
@model Entities.User

@{
    ViewBag.Title = "EditPersonInfo";
}

<h2>Edit your info</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IDUser)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Gender)
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Town, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Town, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Town, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Cancel", "Index")
</div>

NetworkMVC/Views/MainPage/Friends.cshtml
@model IEnumerable<Entities.Friend>

@{
    ViewBag.Title = "Friends";
}

<h2>Friends</h2>

<p>
    @Html.ActionLink("Search By Name", "SearchByName", "Search") / 
    @Html.ActionLink("Search By Surname", "SearchBySurname", "Search") / 
    @Html.ActionLink("Search By Phone", "SearchByPhone", "Search") / 
    @Html.ActionLink("Search By Town", "SearchByTown", "Search")

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th>
            @Html.DisplayName("Man")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Town)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TermOfFriend)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Patronymic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Town)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TermOfFriend)
             <td>
        </td>
        <td>
            @Html.ActionLink("Messages", "Index", "Message", new { id = item.IDUser }, new { })
        </td>
        <td>
            
                <form action="~/Search/Details" method="post">
                    <input type="hidden" name="idUser" id="idUser" value="@item.IDUser" />
                    <button type="submit" name="Remove">Remove</button>
                </form>
        </td>
    </tr>
}

</table>

NetworkMVC/Views/MainPage/GetAllUsers.cshtml
@model IEnumerable<Entities.User>

@{
    ViewBag.Title = "All Users";
}

<h2>All Users</h2>


<form action="~/MainPage/DeleteUsers" method="post" style="margin:5px;">
    <button type="submit" name="Delete">Delete all users</button>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Town)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IDUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patronymic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Town)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
        </tr>
    }

</table>

NetworkMVC/Views/MainPage/Index.cshtml
@model Entities.User

@{
    ViewBag.Title = "Main Page";
}

<h2>Your summary</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patronymic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patronymic)
        </dd>

        <dt>
            @Html.DisplayName("Man")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditPersonInfo", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Log out", "LogOut")
</p>

NetworkMVC/Views/MainPage/SingUp.cshtml
@model Entities.User
@{
    ViewBag.Title = "Sing Up";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    Добро пожаловать в социальную сеть, зарегистрируйтесь!
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Man", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Gender)
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Town, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Town, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Town, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sing up" class="btn btn-default" />
            </div>
        </div>
    </div>
}